site_name: Provara Protocol Documentation
site_url: https://provara.dev/docs/
repo_url: https://github.com/provara-protocol/provara
repo_name: provara-protocol/provara

theme:
  name: material

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  - admonition

nav:
  - Getting Started: getting-started.md
  - Tutorials: tutorials/README.md
  - API Reference: api-reference/index.md
  - Cookbook: cookbook/README.md
  - Protocol Spec: protocol-spec.md
  - Contributing: contributing.md

docs_dir: docs
site_dir: site
